name: SellAllItems
version: 1.0.0
api: [4.0.0, 5.0.0]
main: SellAllItems\SellAllItems
author: NurAzliYT
description: "A plugin to sell all items (except Bedrock) and earn money."

commands:
  sellall:
    description: "Sell all items (except Bedrock) and earn money."
    permission: sellall.items
    usage: /sellall
    aliases: [sall, allsell]

permissions:
  sellall.items:
  default: default
